version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_HOST: %
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: website
          
          

      steps:
        - checkout
        -run: npm install
        -run: node mysql_testing.js
# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build
# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: circleci/node:10.16.3
#       - image: circleci/mysql:8.0.4
#         environment:
#           MYSQL_ROOT_PASSWORD: root
#           MYSQL_DATABASE: property
#           MYSQL_USER: root
#           MYSQL_PASSWORD: root
#     steps:
#       - checkout
#       - run: npm install
#       - run: npm run test
